version: "3"
services:

  ejabberd:
    image: ejabberd/ecs
    restart: always
    volumes:
      - ./conf/ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:z
      - ./conf/ejabberdctl.cfg:/home/ejabberd/conf/ejabberdctl.cfg:z
      - ./ssl:/home/ejabberd/ssl:ro,z
      - ./upload:/home/ejabberd/upload:z
      - ./sqlite:/home/ejabberd/database/sqlite:z
    hostname: myejabberd.com
    ports:
      - "1883:1883"     # mod_mqtt
      - "5222:5222"     # ejabberd_c2s
      - "5269:5269"     # ejabberd_s2s_in
      - "5280:5280"     # ejabberd_http/http
      - "5443:5443"     # ejabberd_http/https
    environment:
      - TZ=Asia/Shanghai

